<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>

    <TargetFramework>net10.0-windows10.0.22621.0</TargetFramework>
    <TargetPlatformMinVersion>10.0.22621.0</TargetPlatformMinVersion>
    <SupportedOSPlatformVersion>10.0.22621.0</SupportedOSPlatformVersion>
    <Platforms>x86;x64;ARM64</Platforms>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <AssemblyName>YumCommu.UI.WrapPanel</AssemblyName>
    <RootNamespace>YumCommu.UI</RootNamespace>
    <RuntimeIdentifiers>win-x86;win-x64;win-arm64</RuntimeIdentifiers>
    <PublishProfile>win-$(Platform).pubxml</PublishProfile>
    <UseWinUI>true</UseWinUI>
    <WinUISDKReferences>false</WinUISDKReferences>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <DefaultLanguage>ja-JP</DefaultLanguage>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AllowUnsafeBlocks>False</AllowUnsafeBlocks>
    <Configurations>Debug;Release;Debug-Packaged;Release-Packaged</Configurations>
    <Packaged>false</Packaged>
    <Packaged Condition="'$(Configuration)' == 'Debug-Packaged' Or '$(Configuration)' == 'Release-Packaged'">true</Packaged>
    <LangVersion>preview</LangVersion>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <Authors>yum communication, Ishina Yum</Authors>
    <Description>WrapPanel conrol for WinUI3</Description>
    <PackageReadmeFile>readme.md</PackageReadmeFile>
    <PackageTags>.NET WinUI3</PackageTags>
    <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/yum-Communication/YumCommu.UI</PackageProjectUrl>
    <Copyright>Copyright ©2026 yum communication Co. Ltd.</Copyright>
    <Version>1.0.1</Version>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Packaged)' != 'true'">
    <EnableMsixTooling>false</EnableMsixTooling>
    <WindowsPackageType>None</WindowsPackageType>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Packaged)' == 'true'">
    <EnableMsixTooling>true</EnableMsixTooling>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Windows.SDK.BuildTools" Version="10.0.28000.1839" />
    <PackageReference Include="Microsoft.WindowsAppSDK" Version="2.2.0" />
    <Manifest Include="$(ApplicationManifest)" />
  </ItemGroup>

  <!--
    Defining the "Msix" ProjectCapability here allows the Single-project MSIX Packaging
    Tools extension to be activated for this project even if the Windows App SDK Nuget
    package has not yet been restored.
  -->
  <ItemGroup Condition="'$(DisableMsixProjectCapabilityAddedByProject)'!='true' and '$(EnableMsixTooling)'=='true'">
    <ProjectCapability Include="Msix" />
  </ItemGroup>
  <ItemGroup>
    <None Include="nuget\readme.md" pack="true" PackagePath="\" />
  </ItemGroup>

  <!--
    Defining the "HasPackageAndPublishMenuAddedByProject" property here allows the Solution
    Explorer "Package and Publish" context menu entry to be enabled for this project even if
    the Windows App SDK Nuget package has not yet been restored.
  -->
  <PropertyGroup Condition="'$(DisableHasPackageAndPublishMenuAddedByProject)'!='true' and '$(EnableMsixTooling)'=='true'">
    <HasPackageAndPublishMenu>true</HasPackageAndPublishMenu>
  </PropertyGroup>
</Project>